#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  bundle install --path vendor/bundle

  FORCE_OPTION=""
  if [ -n "${FORCE}" ] && [ "$FORCE" == "true" ]; then
    FORCE_OPTION="--force"
  fi

  FINAL_OPTION=""
  if [ -n "${FINAL}" ] && [ "$FINAL" == "true" ]; then
    FINAL_OPTION="--final"

    cat >config/private.yml <<EOL
---
blobstore:
  s3:
    access_key_id: ${S3_ACCESS_KEY}
    secret_access_key: ${S3_SECRET_KEY} 
EOL
  fi

  bundle exec bosh -n create release --with-tarball ${FORCE_OPTION} ${FINAL_OPTION} --name ${NAME}
popd
