#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  bundle install --path vendor/bundle

  FORCE_OPTION=""
  if [ -n "${FORCE}" ] && [ "$FORCE" == "true" ]; then
    FORCE_OPTION="--force"
  fi

  FINAL_OPTION=""
  if [ -n "${FINAL}" ] && [ "$FINAL" == "true" ]; then
    FINAL_OPTION="--final"
  fi

  bundle exec bosh create release --with-tarball ${FORCE_OPTION} ${FINAL_OPTION} --name ${NAME}
popd
