#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  git checkout develop

  git config --global user.email "ci@localhost"
  git config --global user.name "CI Bot"

  git merge -m "Merge branch 'master' into develop [ci skip]" master
popd
